djangocrud_first/crud/urls.py
#crud/urls.py
from . import views
from django.urls import path

urlpatterns = [
    #path ('admin/', admin.site.urls), 
    path ('emp', views.emp),
    path ('utilisateurs', views.show),
    path ('edit/<int:id>',views.edit ), 
    path ('update/<int:id>',views.update ), 
    path ('delete/<int:id>',views.destroy ), 
]

djangocrud_first/djangocrud/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include ('crud.urls')),
]

djangocrud_first/crud/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.
class Utilisateurs (models.Model):
    #id = models.IntegerField(unique = True )
    nom = models.CharField (max_length = 200)
    status = models.CharField (max_length = 30)
    mot_de_passe = models.CharField(max_length = 20, unique = True)

    class Meta:
        db_table = 'Utilisateurs'
        """managed = True
        verbose_name = 'ModelName'
        verbose_name_plural = 'ModelNames' """

djangocrud_first/crud/forms.py
from django import forms 
from crud.models import Utilisateurs

# formulaire pour creer un utilisateur 

class UtilisateursForm (forms.ModelForm): 
    class Meta: 
        model = Utilisateurs 
        fields = "__all__"

djangocrud_first/crud/views.py
from django.shortcuts import render, redirect
from crud.forms import UtilisateursForm
from crud.models import Utilisateurs
# Create your views here.

def emp(request): 
    form = UtilisateursForm()
    if request.method == "POST":
        form = UtilisateursForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/utilisateurs')
            except:
                pass
        else: 
             form = UtilisateursForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    utilisateurs = Utilisateurs.objects.all()  
    return render(request,"utilisateur.html",{'utilisateurs':utilisateurs})  
def edit(request, id):  
    utilisateurs = Utilisateurs.objects.get(id=id)  
    return render(request,'edit.html', {'utilisateurs':utilisateurs})  
def update(request, id):  
    utilisateurs = Utilisateurs.objects.get(id=id)  
    form = UtilisateursForm(request.POST, instance = utilisateurs)  
    if request.method == 'POST':
        if form.is_valid():  
            form.save()  
            return redirect("/utilisateurs")  
    return render(request, 'edit.html', {'utilisateurs': utilisateurs, 'form': form})  
def destroy(request, id):  
    utilisateurs = Utilisateurs.objects.get(id=id)  
    utilisateurs.delete()  
    return redirect("/utilisateurs")  
        

djangocrud_first/crud/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookstore - Simple is Better Than Complex</title>
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% comment %} {% include 'includes/header.html' %} {% endcomment %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% comment %} <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>  <!-- JQUERY HERE --> {% endcomment %}
    <script src="{% static 'dist/js/bootstrap.bundle.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

djangocrud_first/crud/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'style/style.css' %}"/>  
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
</head>  
<body>  
  <form method="POST" class="post-form" action="/update/{{employee.id}}">  
          {% csrf_token %}  
    <div class="container">  
        <br>  
      <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
          <h3> Modifier Details</h3>  
        </div>  
      </div>  
      {% comment %} <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Utilisateur Id:</label>  
        <div class="col-sm-4">  
            <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ utilisateur.id }}"/>  
        </div>  
      </div>   {% endcomment %}
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Utilisateur Nom:</label>  
        <div class="col-sm-4">  
            <input type="text" name="nom" id="id_nom" required maxlength="100" value="{{ utilisateur.nom  }}" />  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Utilisateur Status :</label>  
        <div class="col-sm-4">  
            <input type="text" name="status" id="id_status" required maxlength="254" value="{{ utilisateur.status }}" />  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Utilisateur Mot de passe :</label>  
        <div class="col-sm-4">  
            <input type="text" name="mot_de_passe" id="id_mot_de_passe" required maxlength="15" value="{{ utilisateur.mot_de_passe }}" />  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success"> Modifier </button>  
        </div>  
      </div>  
    </div>  
  </form>  


  <script src="{% static 'dist/js/bootstrap.bundle.min.js' %}"></script>
</body>  
</html>  

djangocrud_first/crud/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'style/style.css' %}"/>  
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.min.css' %}" >
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Entrez les informations </h3>  
    </div>  
  </div>  
    {% comment %} <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Utilisateur Id:</label>  
    <div class="col-sm-4">  
      {{ form.id }}  
    </div>   {% endcomment %}
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Utilisateur Nom:</label>  
    <div class="col-sm-4">  
      {{ form.nom }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Utilisateur Status:</label>  
    <div class="col-sm-4">  
      {{ form.status }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Utilisateur Mot de passe :</label>  
    <div class="col-sm-4">  
      {{ form.mot_de_passe }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Envoyer </button>  
    </div>  
  </div>  
    </div>  
</form>  

<script src="{% static 'dist/js/bootstrap.bundle.min.js' %}"></script>
</body>  
</html>  

djangocrud_first/crud/templates/utilisateur.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="page-header">Utilisateurs</h1>
  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Noms</th>
        <th>Status</th>
        <th>Mot de passe </th>
      </tr>
    </thead>
    <tbody>
      {% for utilisateur in utilisateurs  %}
        <tr>
          <td>{{ utilisateur.id }}</td>
          <td>{{ utilisateur.nom }}</td>
          <td>{{ utilisateur.status }}</td>
          <td>{{ utilisateur.mot_de_passe}}</td>
          <td> <a href="{% url 'update' utilisateur.id%}"> <span class="glyficon glyficon-pencil"></span> Modifier</a></td>
          <td> <a href="/delete/{{utilisateur.id}}"> Supprimer </a> </td>

        </tr>
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-warning">Aucun utilisateur </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
{% endblock %}